[package]
name = "minimal-grandpa-runtime"
version = "2.0.0"
edition = "2018"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
description = "A runtime that manages a set of grandpa authorities and supplies them to the client"
license = "GPL-3.0-or-later"

[package.metadata.substrate]
categories = [
	"runtime",
	"GRANDPA",
	"tutorial",
	"recipe",
]
compatibility_version = "2.0.0"

[dependencies]
parity-scale-codec = { version = "1.3.0", features = ["derive"], default-features = false }
serde = { version = "1.0", optional = true, features = ["derive"] }

# Substrate packages

balances = { package = 'pallet-balances', version = '2.0.0', default-features = false }
frame-executive = { version = '2.0.0', default-features = false }
frame-support = { version = '2.0.0', default-features = false }
frame-system = { version = '2.0.0', default-features = false }
grandpa = { package = 'pallet-grandpa', version = '2.0.0', default-features = false }
randomness-collective-flip = { package = 'pallet-randomness-collective-flip', version = '2.0.0', default-features = false }
sp-api = { version = '2.0.0', default-features = false }
sp-block-builder = { version = '2.0.0', default-features = false }
sp-core = { version = '2.0.0', default-features = false }
sp-finality-grandpa = { version = '2.0.0', default-features = false }
sp-inherents = { version = '2.0.0', default-features = false }
sp-io = { version = '2.0.0', default-features = false }
sp-offchain = { version = '2.0.0', default-features = false }
sp-runtime = { version = '2.0.0', default-features = false }
sp-session = { version = '2.0.0', default-features = false }
sp-std = { version = '2.0.0', default-features = false }
sp-transaction-pool = { version = '2.0.0', default-features = false }
sp-version = { version = '2.0.0', default-features = false }
sudo = { package = 'pallet-sudo', version = '2.0.0', default-features = false }
timestamp = { package = 'pallet-timestamp', version = '2.0.0', default-features = false }
transaction-payment = { package = 'pallet-transaction-payment', version = '2.0.0', default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
std = [
	"balances/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"grandpa/std",
	"parity-scale-codec/std",
	"randomness-collective-flip/std",
	"serde",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-finality-grandpa/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"sudo/std",
	"timestamp/std",
	"transaction-payment/std",
]
