[book]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
language = "en"
multilingual = false
src = "text"
title = "Substrate Recipes"
description = "A Hands-On Cookbook for Aspiring Blockchain Chefs"

[output.html]
additional-js = [
  ".analytics/load.js",
  ".analytics/config.js",
  ".analytics/klaro.min.js"
]
theme = "src/theme"
