name: Test Code

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - test-ci # always want to including test-ci for testing gh-action
    paths-ignore:
      - 'README.md'

jobs:
  test-code:
    name: Test
    strategy:
      matrix:
        toolchain:
          - stable
    runs-on:                       ubuntu-18.04
    container:
      image:                       paritytech/ci-linux:e79b7a7e-20200827
    env:
      RUST_BACKTRACE:              full
      CARGO_INCREMENTAL:           0
      CARGO_HOME:                  /github/home/cache/${{ github.head_ref }}/${{ matrix.toolchain }}/cargo
      CARGO_TARGET_DIR:            /github/home/cache/${{ github.head_ref }}/${{ matrix.toolchain }}/target
      SCCACHE_DIR:                 /github/home/cache/${{ github.head_ref }}/${{ matrix.toolchain }}/sccache
      SCCACHE_IDLE_TIMEOUT:        0
      CMAKE_C_COMPILER_LAUNCHER:   sccache
      CMAKE_CXX_COMPILER_LAUNCHER: sccache

    steps:
      - name:                      Cancel previous runs
        uses:                      styfle/cancel-workflow-action@0.4.1
        with:
          access_token:            ${{ github.token }}

      - name:                      Rust version
        shell:                     bash
        run:                       |
          rustup show

      - name:                      Checkout sources & submodules
        uses:                      actions/checkout@v2
        with:
          fetch-depth:             5
          submodules:              recursive

      - name:                      Cache CARGO_HOME, CARGO_TARGET_DIR, SCCACHE_DIR
        uses:                      actions/cache@v2
        with:
          path:                    |
            /github/home/cache/${{ github.head_ref }}/${{ matrix.toolchain }}
          key:                     ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys:            |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-

      - name:                      Cache stats
        shell:                     bash
        run:                       |
          sccache --show-stats
          du -sh /github/home/cache/${{ github.head_ref }}/${{ matrix.toolchain }}/*

      ## --- Test stage ---

      - name:                      Run all recipes tests
        uses:                      actions-rs/cargo@master
        with:
          command:                 test
          args:                    --all --verbose
